# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "David Mims"
resume_title:                   "Computer Science Undergraduate"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "dmmims@email.sc.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "843-822-2293"
resume_contact_address:         "1600 Greene Street, Columbia SC"

resume_header_contact_info:     "1600 Greene Street Apt 12, Columbia SC • 843-822-2293 • dmmims@email.sc.edu"
display_header_contact_info:    "false"

resume_header_intro: "<p>This is the executive summary. You should write a few brief, concise, and meaningful sentences about yourself from a professional context, and your immediate career goals. Make the length appropriate for your needs, but keep it brief and concise</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/dmims"
  resume_twitter_url:           "http://twitter.com/Mimsy98"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/david-mims-9ab03519b"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://dmims.github.io"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
